spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estoque
    username: estoque_user
    password: estoque_pass
  jpa:
    hibernate:
      ddl-auto: validate   # nunca "update" — quem cria/altera tabela é o Flyway
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: oficina